/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyIdRouteImport } from './routes/verify-id'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherAllocationsRouteImport } from './routes/_authenticated/teacher-allocations'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedReportCardsRouteImport } from './routes/_authenticated/report-cards'
import { Route as AuthenticatedRemarksRouteImport } from './routes/_authenticated/remarks'
import { Route as AuthenticatedRecycleBinRouteImport } from './routes/_authenticated/recycle-bin'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedIdCardsRouteImport } from './routes/_authenticated/id-cards'
import { Route as AuthenticatedHomeworkRouteImport } from './routes/_authenticated/homework'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as VerifyTeacherTokenRouteImport } from './routes/verify.teacher.$token'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedPlatformTeachersRouteImport } from './routes/_authenticated/platform/teachers'
import { Route as AuthenticatedPlatformSubscriptionsRouteImport } from './routes/_authenticated/platform/subscriptions'
import { Route as AuthenticatedPlatformStaffRouteImport } from './routes/_authenticated/platform/staff'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform/settings'
import { Route as AuthenticatedPlatformSchoolsRouteImport } from './routes/_authenticated/platform/schools'
import { Route as AuthenticatedPlatformBulkImportRouteImport } from './routes/_authenticated/platform/bulk-import'
import { Route as AuthenticatedPlatformAuditLogsRouteImport } from './routes/_authenticated/platform/audit-logs'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated/admin/whatsapp'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'

const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify-id',
  path: '/verify-id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherAllocationsRoute =
  AuthenticatedTeacherAllocationsRouteImport.update({
    id: '/teacher-allocations',
    path: '/teacher-allocations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportCardsRoute =
  AuthenticatedReportCardsRouteImport.update({
    id: '/report-cards',
    path: '/report-cards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRemarksRoute = AuthenticatedRemarksRouteImport.update({
  id: '/remarks',
  path: '/remarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecycleBinRoute = AuthenticatedRecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIdCardsRoute = AuthenticatedIdCardsRouteImport.update({
  id: '/id-cards',
  path: '/id-cards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeworkRoute = AuthenticatedHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const VerifyTeacherTokenRoute = VerifyTeacherTokenRouteImport.update({
  id: '/verify/teacher/$token',
  path: '/verify/teacher/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedPlatformTeachersRoute =
  AuthenticatedPlatformTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSubscriptionsRoute =
  AuthenticatedPlatformSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformStaffRoute =
  AuthenticatedPlatformStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSchoolsRoute =
  AuthenticatedPlatformSchoolsRouteImport.update({
    id: '/schools',
    path: '/schools',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformBulkImportRoute =
  AuthenticatedPlatformBulkImportRouteImport.update({
    id: '/bulk-import',
    path: '/bulk-import',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformAuditLogsRoute =
  AuthenticatedPlatformAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-id': typeof VerifyIdRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/recycle-bin': typeof AuthenticatedRecycleBinRoute
  '/remarks': typeof AuthenticatedRemarksRoute
  '/report-cards': typeof AuthenticatedReportCardsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/teacher-allocations': typeof AuthenticatedTeacherAllocationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/platform/audit-logs': typeof AuthenticatedPlatformAuditLogsRoute
  '/platform/bulk-import': typeof AuthenticatedPlatformBulkImportRoute
  '/platform/schools': typeof AuthenticatedPlatformSchoolsRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/platform/staff': typeof AuthenticatedPlatformStaffRoute
  '/platform/subscriptions': typeof AuthenticatedPlatformSubscriptionsRoute
  '/platform/teachers': typeof AuthenticatedPlatformTeachersRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/verify/teacher/$token': typeof VerifyTeacherTokenRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-id': typeof VerifyIdRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/homework': typeof AuthenticatedHomeworkRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/parent': typeof AuthenticatedParentRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/recycle-bin': typeof AuthenticatedRecycleBinRoute
  '/remarks': typeof AuthenticatedRemarksRoute
  '/report-cards': typeof AuthenticatedReportCardsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/teacher-allocations': typeof AuthenticatedTeacherAllocationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/platform/audit-logs': typeof AuthenticatedPlatformAuditLogsRoute
  '/platform/bulk-import': typeof AuthenticatedPlatformBulkImportRoute
  '/platform/schools': typeof AuthenticatedPlatformSchoolsRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/platform/staff': typeof AuthenticatedPlatformStaffRoute
  '/platform/subscriptions': typeof AuthenticatedPlatformSubscriptionsRoute
  '/platform/teachers': typeof AuthenticatedPlatformTeachersRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/verify/teacher/$token': typeof VerifyTeacherTokenRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-id': typeof VerifyIdRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/homework': typeof AuthenticatedHomeworkRoute
  '/_authenticated/id-cards': typeof AuthenticatedIdCardsRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/recycle-bin': typeof AuthenticatedRecycleBinRoute
  '/_authenticated/remarks': typeof AuthenticatedRemarksRoute
  '/_authenticated/report-cards': typeof AuthenticatedReportCardsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/teacher-allocations': typeof AuthenticatedTeacherAllocationsRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/platform/audit-logs': typeof AuthenticatedPlatformAuditLogsRoute
  '/_authenticated/platform/bulk-import': typeof AuthenticatedPlatformBulkImportRoute
  '/_authenticated/platform/schools': typeof AuthenticatedPlatformSchoolsRoute
  '/_authenticated/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/platform/staff': typeof AuthenticatedPlatformStaffRoute
  '/_authenticated/platform/subscriptions': typeof AuthenticatedPlatformSubscriptionsRoute
  '/_authenticated/platform/teachers': typeof AuthenticatedPlatformTeachersRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/verify/teacher/$token': typeof VerifyTeacherTokenRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-id'
    | '/achievements'
    | '/admin'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/change-password'
    | '/classes'
    | '/dashboard'
    | '/fees'
    | '/homework'
    | '/id-cards'
    | '/invitations'
    | '/leaves'
    | '/marks'
    | '/notifications'
    | '/parent'
    | '/payroll'
    | '/platform'
    | '/recycle-bin'
    | '/remarks'
    | '/report-cards'
    | '/students'
    | '/super-admin'
    | '/teacher-allocations'
    | '/admin/billing'
    | '/admin/whatsapp'
    | '/platform/audit-logs'
    | '/platform/bulk-import'
    | '/platform/schools'
    | '/platform/settings'
    | '/platform/staff'
    | '/platform/subscriptions'
    | '/platform/teachers'
    | '/students/$studentId'
    | '/verify/teacher/$token'
    | '/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-id'
    | '/achievements'
    | '/admin'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/change-password'
    | '/classes'
    | '/dashboard'
    | '/fees'
    | '/homework'
    | '/id-cards'
    | '/invitations'
    | '/leaves'
    | '/marks'
    | '/notifications'
    | '/parent'
    | '/payroll'
    | '/recycle-bin'
    | '/remarks'
    | '/report-cards'
    | '/students'
    | '/super-admin'
    | '/teacher-allocations'
    | '/admin/billing'
    | '/admin/whatsapp'
    | '/platform/audit-logs'
    | '/platform/bulk-import'
    | '/platform/schools'
    | '/platform/settings'
    | '/platform/staff'
    | '/platform/subscriptions'
    | '/platform/teachers'
    | '/students/$studentId'
    | '/verify/teacher/$token'
    | '/platform'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-id'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/announcements'
    | '/_authenticated/attendance'
    | '/_authenticated/change-password'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/fees'
    | '/_authenticated/homework'
    | '/_authenticated/id-cards'
    | '/_authenticated/invitations'
    | '/_authenticated/leaves'
    | '/_authenticated/marks'
    | '/_authenticated/notifications'
    | '/_authenticated/parent'
    | '/_authenticated/payroll'
    | '/_authenticated/platform'
    | '/_authenticated/recycle-bin'
    | '/_authenticated/remarks'
    | '/_authenticated/report-cards'
    | '/_authenticated/students'
    | '/_authenticated/super-admin'
    | '/_authenticated/teacher-allocations'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/platform/audit-logs'
    | '/_authenticated/platform/bulk-import'
    | '/_authenticated/platform/schools'
    | '/_authenticated/platform/settings'
    | '/_authenticated/platform/staff'
    | '/_authenticated/platform/subscriptions'
    | '/_authenticated/platform/teachers'
    | '/_authenticated/students/$studentId'
    | '/verify/teacher/$token'
    | '/_authenticated/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyIdRoute: typeof VerifyIdRoute
  VerifyTeacherTokenRoute: typeof VerifyTeacherTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-id': {
      id: '/verify-id'
      path: '/verify-id'
      fullPath: '/verify-id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher-allocations': {
      id: '/_authenticated/teacher-allocations'
      path: '/teacher-allocations'
      fullPath: '/teacher-allocations'
      preLoaderRoute: typeof AuthenticatedTeacherAllocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report-cards': {
      id: '/_authenticated/report-cards'
      path: '/report-cards'
      fullPath: '/report-cards'
      preLoaderRoute: typeof AuthenticatedReportCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/remarks': {
      id: '/_authenticated/remarks'
      path: '/remarks'
      fullPath: '/remarks'
      preLoaderRoute: typeof AuthenticatedRemarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recycle-bin': {
      id: '/_authenticated/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/recycle-bin'
      preLoaderRoute: typeof AuthenticatedRecycleBinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/id-cards': {
      id: '/_authenticated/id-cards'
      path: '/id-cards'
      fullPath: '/id-cards'
      preLoaderRoute: typeof AuthenticatedIdCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/homework': {
      id: '/_authenticated/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof AuthenticatedHomeworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/verify/teacher/$token': {
      id: '/verify/teacher/$token'
      path: '/verify/teacher/$token'
      fullPath: '/verify/teacher/$token'
      preLoaderRoute: typeof VerifyTeacherTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/platform/teachers': {
      id: '/_authenticated/platform/teachers'
      path: '/teachers'
      fullPath: '/platform/teachers'
      preLoaderRoute: typeof AuthenticatedPlatformTeachersRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/subscriptions': {
      id: '/_authenticated/platform/subscriptions'
      path: '/subscriptions'
      fullPath: '/platform/subscriptions'
      preLoaderRoute: typeof AuthenticatedPlatformSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/staff': {
      id: '/_authenticated/platform/staff'
      path: '/staff'
      fullPath: '/platform/staff'
      preLoaderRoute: typeof AuthenticatedPlatformStaffRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/settings': {
      id: '/_authenticated/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/schools': {
      id: '/_authenticated/platform/schools'
      path: '/schools'
      fullPath: '/platform/schools'
      preLoaderRoute: typeof AuthenticatedPlatformSchoolsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/bulk-import': {
      id: '/_authenticated/platform/bulk-import'
      path: '/bulk-import'
      fullPath: '/platform/bulk-import'
      preLoaderRoute: typeof AuthenticatedPlatformBulkImportRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/audit-logs': {
      id: '/_authenticated/platform/audit-logs'
      path: '/audit-logs'
      fullPath: '/platform/audit-logs'
      preLoaderRoute: typeof AuthenticatedPlatformAuditLogsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformAuditLogsRoute: typeof AuthenticatedPlatformAuditLogsRoute
  AuthenticatedPlatformBulkImportRoute: typeof AuthenticatedPlatformBulkImportRoute
  AuthenticatedPlatformSchoolsRoute: typeof AuthenticatedPlatformSchoolsRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedPlatformStaffRoute: typeof AuthenticatedPlatformStaffRoute
  AuthenticatedPlatformSubscriptionsRoute: typeof AuthenticatedPlatformSubscriptionsRoute
  AuthenticatedPlatformTeachersRoute: typeof AuthenticatedPlatformTeachersRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformAuditLogsRoute: AuthenticatedPlatformAuditLogsRoute,
  AuthenticatedPlatformBulkImportRoute: AuthenticatedPlatformBulkImportRoute,
  AuthenticatedPlatformSchoolsRoute: AuthenticatedPlatformSchoolsRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedPlatformStaffRoute: AuthenticatedPlatformStaffRoute,
  AuthenticatedPlatformSubscriptionsRoute:
    AuthenticatedPlatformSubscriptionsRoute,
  AuthenticatedPlatformTeachersRoute: AuthenticatedPlatformTeachersRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedHomeworkRoute: typeof AuthenticatedHomeworkRoute
  AuthenticatedIdCardsRoute: typeof AuthenticatedIdCardsRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
  AuthenticatedRecycleBinRoute: typeof AuthenticatedRecycleBinRoute
  AuthenticatedRemarksRoute: typeof AuthenticatedRemarksRoute
  AuthenticatedReportCardsRoute: typeof AuthenticatedReportCardsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedTeacherAllocationsRoute: typeof AuthenticatedTeacherAllocationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedHomeworkRoute: AuthenticatedHomeworkRoute,
  AuthenticatedIdCardsRoute: AuthenticatedIdCardsRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
  AuthenticatedRecycleBinRoute: AuthenticatedRecycleBinRoute,
  AuthenticatedRemarksRoute: AuthenticatedRemarksRoute,
  AuthenticatedReportCardsRoute: AuthenticatedReportCardsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedTeacherAllocationsRoute: AuthenticatedTeacherAllocationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyIdRoute: VerifyIdRoute,
  VerifyTeacherTokenRoute: VerifyTeacherTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
